Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WMS_FE.Controllers
{
    public class DashboardController : Controller
    {
        // GET: Dashboard
        public ActionResult Index()
        {
            String token = this.Request.QueryString["t"];
            Session["token"] = token;
            String username = this.Request.QueryString["u"];
            Session["username"] = username;
            String rememberMe = this.Request.QueryString["r"];
            if (rememberMe == "true")
            {
                HttpContext.Session.Timeout = 525600;
            }
            else
            {
                HttpContext.Session.Timeout = 60;
            }

            return View();
        }
    }
}

Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WMS_FE.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {
            Session["token"] = null;
            Session["username"] = null;

            ViewBag.Server = ConfigurationManager.AppSettings["server"].ToString();
            ViewBag.BaseUrl = Request.Url.Scheme + "://" + Request.Url.Authority + Request.ApplicationPath.TrimEnd('/');
            return View();
        }
    }
}

Controllers/PurchaseRequestController.cs
using iText.Html2pdf;
using iText.Kernel.Geom;
using iText.Kernel.Pdf;
using iText.Layout;
using iText.Layout.Element;
using iText.Layout.Properties;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WMS_FE.Models;

namespace WMS_FE.Controllers
{
    public class PurchaseRequestController : Controller
    {
        // GET: ProductionPlan
        public ActionResult Index()
        {
            if (Session["token"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            ViewBag.BaseUrl = Request.Url.Scheme + "://" + Request.Url.Authority + Request.ApplicationPath.TrimEnd('/');
            ViewBag.Server = ConfigurationManager.AppSettings["server"].ToString();
            return View();
        }

        public ActionResult Create()
        {
            if (Session["token"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            ViewBag.BaseUrl = Request.Url.Scheme + "://" + Request.Url.Authority + Request.ApplicationPath.TrimEnd('/');
            ViewBag.Server = ConfigurationManager.AppSettings["server"].ToString();
            return View();
        }

        public ActionResult Edit()
        {
            if (Session["token"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            ViewBag.BaseUrl = Request.Url.Scheme + "://" + Request.Url.Authority + Request.ApplicationPath.TrimEnd('/');
            ViewBag.Param = this.Request.QueryString["id"];
            ViewBag.Server = ConfigurationManager.AppSettings["server"].ToString();
            return View();
        }

        // GET: PDF
        public async Task<ActionResult> PDF(string id)
        {
            try
            {
                if (string.IsNullOrEmpty(id))
                {
                    throw new Exception();
                }
                else
                {
                    //get data api
                    string Domain = Request.Url.Scheme + "://" + Request.Url.Authority + Request.ApplicationPath.TrimEnd('/');
                    string ApiAddress = ConfigurationManager.AppSettings["server"].ToString();


                    HttpClient client = new HttpClient();
                    Uri uri = new Uri(ApiAddress + string.Format("Api/PurchaseRequest/ExcelDataById?id={0}", id));
                    var response = await client.GetAsync(uri);
                    string result = response.Content.ReadAsStringAsync().Result;
                    PurchaseRequestResponse res = JsonConvert.DeserializeObject<PurchaseRequestResponse>(result);

                    PurchaseRequestHeaderDTO purchaseRequest = res.data;

                    string viewName = "";
                    string title = "";

                    switch (res.data.SourceType)
                    {
                        case "VENDOR":
                            viewName = "PR_Vendor";
                            title = "PURCHASING REQUEST";
                            break;
                        case "IMPORT":
                            viewName = "PR_Vendor";
                            title = "PURCHASING REQUEST";
                            break;
                        case "CUSTOMER":
                            viewName = "PR_Customer";
                            title = "RM CUSTOMER SUPPLIED";
                            break;
                        case "OUTSOURCE":
                            viewName = "PR_Outsource";
                            title = "DELIVERY NOTE";
                            break;
                    };

                    ViewBag.Title = title;
                    ViewBag.Logo = Domain + "/Content/img/logo.jpg";
                    String body = Helper.RenderViewToString(this.ControllerContext, viewName, purchaseRequest);
                    using (MemoryStream stream = new System.IO.MemoryStream())
                    {
                        using (var pdfWriter = new PdfWriter(stream))
                        {
                            PdfDocument pdf = new PdfDocument(pdfWriter);
                            Document document = new Document(pdf);
                            if (!res.data.SourceType.Equals("OUTSOURCE"))
                            {
                                document = new Document(pdf, PageSize.A4.Rotate());
                            }


                            //int numberOfPages = pdf.GetNumberOfPages();
                            //for (int i = 1; i <= numberOfPages; i++)
                            //{

                            //    // Write aligned text to the specified by parameters point
                            //    document.ShowTextAligned(new Paragraph(String.Format("page %s of %s", i, numberOfPages)),
                            //            559, 806, i, TextAlignment.RIGHT, VerticalAlignment.BOTTOM, 0);
                            //}

                            HtmlConverter.ConvertToPdf(body, pdf, null);
                            byte[] file = stream.ToArray();
                            MemoryStream output = new MemoryStream();
                            output.Write(file, 0, file.Length);
                            output.Position = 0;

                            Response.AddHeader("content-disposition", "inline; filename=form.pdf");
                            // Return the output stream
                            return File(output, "application/pdf");
                        }
                    }
                }
            }
            catch (Exception e)
            {
                return Content(@"<body>
                       <script type='text/javascript'>
                         window.close();
                       </script>
                     </body> ");
            }
        }


    }
}

Views/Shared/_Auth.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>RMI - @ViewBag.Title</title>
    <link rel="icon" href="@Url.Content("~/Content/img/logo.png")">

    @Styles.Render("~/bundles/css")
    @Styles.Render("~/Content/plugins/fontawesome-free/css/all.min.css")
    @Styles.Render("~/Content/plugins/icon-kit/dist/css/iconkit.min.css")
    @Styles.Render("~/Content/plugins/toastr/toastr.css")
    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:300,400,600,700,800" rel="stylesheet">

    <style>
        #preloader {
            position: fixed;
            width: 100%;
            height: 100%;
            left: 0;
            top: 0;
            z-index: 999999999;
            background-color: rgba(0,0,0,0.5) !important;
        }

        .sk-cube-grid {
            width: 40px;
            height: 40px;
            margin: 250px auto;
        }

        .sk-cube-grid .sk-cube {
            width: 33%;
            height: 33%;
            background-color: #007bff;
            float: left;
            -webkit-animation: sk-cubeGridScaleDelay 1.3s infinite ease-in-out;
            animation: sk-cubeGridScaleDelay 1.3s infinite ease-in-out;
        }

        .sk-cube-grid .sk-cube1 {
            -webkit-animation-delay: 0.2s;
                    animation-delay: 0.2s;
        }

        .sk-cube-grid .sk-cube2 {
            -webkit-animation-delay: 0.3s;
                    animation-delay: 0.3s;
        }

        .sk-cube-grid .sk-cube3 {
            -webkit-animation-delay: 0.4s;
                    animation-delay: 0.4s;
        }

        .sk-cube-grid .sk-cube4 {
            -webkit-animation-delay: 0.1s;
                    animation-delay: 0.1s;
        }

        .sk-cube-grid .sk-cube5 {
            -webkit-animation-delay: 0.2s;
                    animation-delay: 0.2s;
        }

        .sk-cube-grid .sk-cube6 {
            -webkit-animation-delay: 0.3s;
                    animation-delay: 0.3s;
        }

        .sk-cube-grid .sk-cube7 {
            -webkit-animation-delay: 0s;
                    animation-delay: 0s;
        }

        .sk-cube-grid .sk-cube8 {
            -webkit-animation-delay: 0.1s;
                    animation-delay: 0.1s;
        }

        .sk-cube-grid .sk-cube9 {
            -webkit-animation-delay: 0.2s;
                    animation-delay: 0.2s;
        }

        @@-webkit-keyframes sk-cubeGridScaleDelay {
            0%, 70%, 100% {
                -webkit-transform: scale3D(1, 1, 1);
                        transform: scale3D(1, 1, 1);
            }
            35% {
                -webkit-transform: scale3D(0, 0, 1);
                        transform: scale3D(0, 0, 1);
            }
        }

        @@keyframes sk-cubeGridScaleDelay {
            0%, 70%, 100% {
                -webkit-transform: scale3D(1, 1, 1);
                        transform: scale3D(1, 1, 1);
            }
            35% {
                -webkit-transform: scale3D(0, 0, 1);
                        transform: scale3D(0, 0, 1);
            }
        }
    </style>
    @RenderSection("custom_css", required: false)


</head>

<body>
    @RenderBody()

    @Scripts.Render("~/bundles/js")
    @Scripts.Render("~/Content/plugins/toastr/toastr.min.js")
    @RenderSection("custom_js", required: false)


    <script type="text/javascript">
        function checkSession() {
            var token = window.localStorage.getItem("token");
            var username = window.localStorage.getItem("username");
            var rememberMe = window.localStorage.getItem("rememberMe");

            if (token != null && username != null && rememberMe != null) {
                window.location.replace(baseUrl + '/Dashboard?t=' + token + '&u=' + username + '&r=' + rememberMe);
            }
        }
        checkSession();
    </script>


</body>

</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>RMI - @ViewBag.Title</title>
    <link rel="icon" href="@Url.Content("~/Content/img/logo.png")">

    @Styles.Render("~/bundles/css")
    @Styles.Render("~/Content/plugins/fontawesome-free/css/all.min.css")
    @Styles.Render("~/Content/plugins/icon-kit/dist/css/iconkit.min.css")
    @*@Styles.Render("~/Content/plugins/datatables/dataTables.bootstrap4.min.css")*@
    @*@Styles.Render("~/Content/plugins/datatables/fixedColumns.bootstrap4.min.css")*@
    @Styles.Render("~/Content/plugins/toastr/toastr.css")
    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:300,400,600,700,800" rel="stylesheet">

    <style>
        #preloader {
            position: fixed;
            width: 100%;
            height: 100%;
            left: 0;
            top: 0;
            z-index: 999999999;
            background-color: rgba(0,0,0,0.5) !important;
        }
        .sk-cube-grid {
            width: 40px;
            height: 40px;
            margin: 250px auto;
        }
        .sk-cube-grid .sk-cube {
            width: 33%;
            height: 33%;
            background-color: #007bff;
            float: left;
            -webkit-animation: sk-cubeGridScaleDelay 1.3s infinite ease-in-out;
                    animation: sk-cubeGridScaleDelay 1.3s infinite ease-in-out; 
        }
        .sk-cube-grid .sk-cube1 {
            -webkit-animation-delay: 0.2s;
                    animation-delay: 0.2s; 
        }
        .sk-cube-grid .sk-cube2 {
            -webkit-animation-delay: 0.3s;
                    animation-delay: 0.3s; 
        }
        .sk-cube-grid .sk-cube3 {
            -webkit-animation-delay: 0.4s;
                    animation-delay: 0.4s; 
        }
        .sk-cube-grid .sk-cube4 {
            -webkit-animation-delay: 0.1s;
                    animation-delay: 0.1s;
        }
        .sk-cube-grid .sk-cube5 {
            -webkit-animation-delay: 0.2s;
                    animation-delay: 0.2s;
        }
        .sk-cube-grid .sk-cube6 {
            -webkit-animation-delay: 0.3s;
                    animation-delay: 0.3s; 
        }
        .sk-cube-grid .sk-cube7 {
            -webkit-animation-delay: 0s;
                    animation-delay: 0s;
        }
        .sk-cube-grid .sk-cube8 {
            -webkit-animation-delay: 0.1s;
                    animation-delay: 0.1s; 
        }
        .sk-cube-grid .sk-cube9 {
            -webkit-animation-delay: 0.2s;
                    animation-delay: 0.2s; 
        }

        @@-webkit-keyframes sk-cubeGridScaleDelay {
          0%, 70%, 100% {
            -webkit-transform: scale3D(1, 1, 1);
                    transform: scale3D(1, 1, 1);
          } 35% {
            -webkit-transform: scale3D(0, 0, 1);
                    transform: scale3D(0, 0, 1); 
          }
        }

        @@keyframes sk-cubeGridScaleDelay {
          0%, 70%, 100% {
            -webkit-transform: scale3D(1, 1, 1);
                    transform: scale3D(1, 1, 1);
          } 35% {
            -webkit-transform: scale3D(0, 0, 1);
                    transform: scale3D(0, 0, 1);
          } 
        }
    </style>
    @RenderSection("custom_css", required: false)


</head>

<body>
    <div id="preloader" style="display:none;">
        <div class="sk-cube-grid">
            <div class="sk-cube sk-cube1"></div>
            <div class="sk-cube sk-cube2"></div>
            <div class="sk-cube sk-cube3"></div>
            <div class="sk-cube sk-cube4"></div>
            <div class="sk-cube sk-cube5"></div>
            <div class="sk-cube sk-cube6"></div>
            <div class="sk-cube sk-cube7"></div>
            <div class="sk-cube sk-cube8"></div>
            <div class="sk-cube sk-cube9"></div>
        </div>
    </div>
    <div class="wrapper">
        <header class="header-top" header-theme="blue">
            <div class="container-fluid">
                <div class="d-flex justify-content-between fa-pull-left">
                    <div class="top-menu d-flex align-items-center">
                        <button type="button" class="btn-icon mobile-nav-toggle d-lg-none"><span></span></button>
                    </div>
                </div>
                <div class="d-flex justify-content-between fa-pull-right">
                    <div class="top-menu d-flex align-items-center">
                        <div class="dropdown">
                            <a class="dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><img class="avatar" src="@Url.Content("~/Content/img/user.png")" alt=""></a>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                                <a class="dropdown-item" href=""><i class="ik ik-user dropdown-icon"></i> Profile</a>
                                <a class="dropdown-item" onclick="(e) => e.preventDefault(); window.localStorage.removeItem('token'); window.localStorage.removeItem('username'); window.localStorage.removeItem('rememberMe'); window.location.replace('@Url.Action("Index", "Login")')" href="@Url.Action("Index", "Login")"><i class="ik ik-power dropdown-icon"></i> Logout</a>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </header>

        <div class="page-wrap">
            <div class="app-sidebar colored">
                <div class="sidebar-header">
                    <a class="header-brand" href="">
                        <div class="logo-img">
                            <img style="width:30px;height:30px;" src="@Url.Content("~/Content/img/logo.jpg")" class="header-brand-img" alt="logo">
                        </div>
                        <span class="text">RM Inventory</span>
                    </a>
                    <button type="button" class="nav-toggle"><i data-toggle="expanded" class="ik ik-toggle-right toggle-icon"></i></button>
                    <button id="sidebarClose" class="nav-close"><i class="ik ik-x"></i></button>
                </div>

                @*all menu open new tab, focus new tab*@
                <div class="sidebar-content">
                    <div class="nav-container">
                        <nav id="main-menu-navigation" class="navigation-main">
                            <div class="nav-lavel">Navigation</div>
                            <div class="nav-item active">
                                <a href="@Url.Action("Index", "Dashboard")"><i class="ik ik-bar-chart-2"></i><span>Dashboard</span></a>
                            </div>
                            <div class="nav-item has-sub">
                                <a href="#"><i class="ik ik-database"></i><span>Logistic</span></a>
                                <div class="submenu-content">
                                    <a href="@Url.Action("Index", "PurchaseRequest")" class="menu-item">Purchase Request</a>
                                </div>
                            </div>
                        </nav>
                    </div>
                </div>
            </div>
            <div class="main-content">
                <div class="container-fluid">
                    @RenderBody()
                </div>
            </div>


            <footer class="footer">
                <div class="w-100 clearfix">
                    <span class="text-center text-sm-left d-md-inline-block">Copyright © @DateTime.Now.Year <b>PT. Elastomix Indonesia</b></span>
                    @*<span class="float-none float-sm-right mt-1 mt-sm-0 text-center text-warning">Powered by PT. Duta Kalingga Pratama</span>*@
                </div>
            </footer>

        </div>
    </div>


    @Scripts.Render("~/bundles/js")
    @*@Scripts.Render("~/Content/plugins/datatables/jquery.dataTables.min.js")*@
    @*@Scripts.Render("~/Content/plugins/datatables/dataTables.bootstrap4.min.js")*@
    @*@Scripts.Render("~/Content/plugins/datatables/dataTables.fixedColumns.min.js")*@
    @Scripts.Render("~/Content/plugins/toastr/toastr.min.js")
    @Scripts.Render("~/Content/custom/js/notification.js")
    <script>
        getPermission('@ViewBag.Module', '@ViewBag.Method');
        function getPermission(module, method) {
            $.ajax({
                type: 'POST',
                dataType: "json",
                beforeSend: function (request) {
                    request.setRequestHeader('Token', '@Session["token"]');
                },
                url: '@ViewBag.Server' + 'Api/Permission/CheckPermission',
                data: {
                    MenuName: module,
                    ControlName: method,
                },
                success: function (response) {
                    isValid = response.status;
                }
            });
        };
    </script>
    <script>
        var preloader = $('#preloader');
        $(document).ajaxStart(function () {
            preloader.show();
        }).ajaxStop(function () {
            preloader.hide();
        });
    </script>
    @RenderSection("custom_js", required: false)


</body>

</html>